apiVersion: v1
kind: Service
metadata:
    name: "{{ service-name }}"
    labels:
      app: "{{ app }}"
spec:
  ports:
{{#ifeq istio-approach true}}
  - name: locpick-api
    port: 8080
    protocol: TCP
    targetPort: 8080
{{/ifeq}}
{{#ifneq istio-approach true}}
  - name: locpick-api
    port: 50002
    protocol: TCP
    targetPort: 50002
{{/ifneq}}
  - name: envoy-admin
    port: 50011
    protocol: TCP
    targetPort: 50011
  clusterIP:  None
  selector:
    app: "{{ app }}"

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: "{{ service-name }}"
spec:
  selector:
    matchLabels:
      app: "{{ app }}"
  serviceName: "{{ service-name }}"
  replicas: {{ replicas }}
  template:
    metadata:
      labels:
        app: "{{ app }}"
        dev: dev
    spec:
      containers:
      - name: beacon
        image: beatrak/beacon
        imagePullPolicy: IfNotPresent
        env:
          - name: "LOG_LEVEL"
            value: "{{ log-level }}"
          - name: "SERVICE_NAME"
            value: "{{ service-name }}"
          - name: "ZONE"
            value: "{{ zone }}"
          - name: "BEACON_SIG_NUMBER"
            value: "{{ beacon-sig-number }}"
          - name: "BEACON_SIG_PS"

{{#ifeq istio-approach true}}
            value: "{{ beacon-sig-ps }}"
          - name: "LOCPICK_HTTP_HOST"
            value: "locpick-dep-hlsvc"
          - name: "LOCPICK_GRPC_HOST"
            value: "locpick-dep-hlsvc"
          - name: "LOCPICK_HTTP_PORT"
            value: "8080"
          - name: "LOCPICK_GRPC_PORT"
            value: "8085"
          - name: "BEACON_HTTP_PORT"
            value: "8080"
          - name: "ELASTIC_HOST"
            value: "elastic-ss-hlsvc"
          - name: "STAGE1_HOST"
            value: "stage1-ss-hlsvc"
          - name: "STAGE1_PORT"
            value: "50006"
{{/ifeq}}
{{#ifneq istio-approach true}}
      - name: envoy
        image: beatrak/beacon-envoy
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 50002
            name: beacon-api
            protocol: TCP
          - containerPort: 50011
            name: envoy-admin
            protocol: TCP
{{/ifneq}}
