apiVersion: v1
kind: Service
metadata:
    name: {{ service-name }}
    labels:
      app: {{ app }}
spec:
  ports:
{{#ifeq istio-approach true}}
  - name: locpick-api
    port: 8080
    protocol: TCP
    targetPort: 8080
{{/ifeq}}
{{#ifneq istio-approach true}}
  - name: locpick-api
    port: 50002
    protocol: TCP
    targetPort: 50002
{{/ifneq}}
  - name: envoy-admin
    port: 50011
    protocol: TCP
    targetPort: 50011
  type: ClusterIP
  clusterIP:  None
  selector:
    app: {{ app }}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ service-name }}
spec:
  selector:
    matchLabels:
      app: "{{ app }}"
  serviceName: "{{ service-name }}"
  replicas: {{ replicas }}
  template:
    metadata:
      labels:
        app: "{{ app }}"
    spec:
      containers:
      - name: beacon
        image: beatrak/beacon-devshell
        imagePullPolicy: IfNotPresent
        env:
          - name: "LOG_LEVEL"
            value: "{{ log-level }}"
          - name: "SERVICE_NAME"
            value: "{{ service-name }}"
          - name: "ZONE"
            value: "{{ zone }}"
          - name: "BEACON_SIG_NUMBER"
            value: "{{ beacon-sig-number }}"
          - name: "BEACON_SIG_PS"
            value: "{{ beacon-sig-ps }}"
        ports:
        - containerPort: 8080
          name: stage1-api
          protocol: TCP
        volumeMounts:
          - mountPath: /root/app
            name: app-volume
          - mountPath: /root/common
            name: common-volume
      - name: envoy
        image: beatrak/beacon-envoy
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50006
          name: stage1-api
          protocol: TCP
        - containerPort: 50011
          name: envoy-admin
          protocol: TCP
      volumes:
        - name: app-volume
          hostPath:
            path: "{{ app-volume-path }}"
        - name: common-volume
          hostPath:
            path: "{{ common-volume-path }}"
      nodeSelector:
        kubernetes.io/hostname: "{{ hostname }}"

