apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ service-name }}
spec:
  selector:
    matchLabels:
      app: {{ app }}
  serviceName: {{ service-name }}
  replicas: {{ replicas }}
  template:
    metadata:
      labels:
        app: {{ app }}
        clusterId: {{ cluster }}
    spec:
      containers:
      - name: stage1
        image: beatrak/stage1-devshell
        imagePullPolicy: IfNotPresent
        env:
          - name: "LOG_LEVEL"
            value: {{ log-level }}
          - name: "SERVICE_NAME"
            value: {{ service-name }}
          - name: "CLUSTER"
            value: {{ cluster }}
          - name: "ZONE"
            value: {{ zone }}
        ports:
        - containerPort: 8080
          name: stage1-api
          protocol: TCP
        volumeMounts:
          - mountPath: /root/app
            name: app-volume
          - mountPath: /root/common
            name: common-volume
{{#unless istio-approach}}
      - name: envoy
        image: beatrak/stage1-envoy
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50006
          name: stage1-api
          protocol: TCP
        - containerPort: 50011
          name: envoy-admin
          protocol: TCP
      volumes:
        - name: app-volume
          hostPath:
            path: {{ app-volume-path }}
        - name: common-volume
          hostPath:
            path: {{ common-volume-path }}
      nodeSelector:
        kubernetes.io/hostname: {{ hostname }}
{{/unless}}




